releases:
- name: jumpbox
  version: 5.1.4
  url: https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v5.1.4/jumpbox-5.1.4.tgz
  sha1: 14e192b7355b3d1348c61850b6396c3f3e602556
