releases:
- name: jumpbox
  version: 5.0.5
  url: https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v5.0.5/jumpbox-5.0.5.tgz
  sha1: 17266c70feeb3f74f545b6e6a015440f4be41786
