- type: replace
  path: /releases?/name=jumpbox?
  value:
    name:    jumpbox
    version: 4.9.1
    url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.9.1/jumpbox-4.9.1.tgz
    sha1:    7f989d74cf0cbb5192541a2e95c33acc6b999966
