- type: replace
  path: /releases?/name=openvpn?
  value:
    name: openvpn
    version: 5.7.0
    url: https://bosh.io/d/github.com/dpb587/openvpn-bosh-release?v=5.7.0
    sha1: 2e57dcaa3689a47c3ab99b56437a396059855869
