releases:
- name:    toolbelt
  version: 3.7.1
  url:     https://github.com/cloudfoundry-community/toolbelt-boshrelease/releases/download/v3.7.1/toolbelt-3.7.1.tgz
  sha1:    be140444c62cfbfcc9a809b0a343e3736fac6e9d
