---
meta:
  ocfp:
    env:
      cloud:     (( concat genesis.env "." genesis.type "." ))

params:
  jumpbox_vm_type:   (( concat meta.ocfp.env.cloud "vm-jumpbox" ))
  jumpbox_disk_type: (( concat meta.ocfp.env.cloud "disk-jumpbox" ))
  jumpbox_network:   (( concat meta.ocfp.env.cloud "net-jumpbox" ))

