#!/bin/bash

# Cloud Config checks
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
  if ! want_feature proto; then
    cloud_config_needs vm_type    $(lookup params.jumpbox_vm_type   jumpbox)
    cloud_config_needs disk_type  $(lookup params.jumpbox_disk_pool jumpbox)
    cloud_config_needs network    $(lookup params.jumpbox_network   jumpbox)
    check_cloud_config && describe "  cloud-config [#G{OK}]"
  fi
fi
