#!/bin/bash
set -eu

cidr2mask() {
  local i mask=""
  local full_octets=$(($1/8))
  local partial_octet=$(($1%8))

  for ((i=0;i<4;i+=1)); do
    if [ $i -lt $full_octets ]; then
      mask+=255
    elif [ $i -eq $full_octets ]; then
      mask+=$((256 - 2**(8-$partial_octet)))
    else
      mask+=0
    fi  
    test $i -lt 3 && mask+=.
  done

  echo $mask
}

prompt_for openvpn boolean \
  'Would you like to use OpenVPN to better control user access?'

if [[ $openvpn == 'true' ]]; then
  prompt_for vpn_client_routes multi-line \
    'What routes should OpenVPN push to connecting clients?  (CIDR format e.g. 10.4.0.0/16)' \
    --min 1

  prompt_for vpn_dns_servers multi-line \
    'What DNS servers should OpenVPN advertise to connecting clients?' \
    --min 1

  prompt_for vpn_dns_search_domains multi-line \
    'What DNS search domains should OpenVPN advertise to connecting clients?' \
    --min 1
fi

trap "rm -f $GENESIS_ROOT/.$GENESIS_ENVIRONMENT.yml" INT QUIT TERM EXIT
(
echo "kit:"
echo "  name:    $GENESIS_KIT_NAME"
echo "  version: $GENESIS_KIT_VERSION"
echo "  features:"
echo "    - (( replace ))"
if [[ $openvpn == 'true' ]]; then
  echo "    - openvpn"
fi
echo

echo "params:"
echo "  env: $GENESIS_ENVIRONMENT"
echo
if [[ $openvpn == 'true' ]]; then
  echo "  vpn_client_routes:"
  for route in ${vpn_client_routes[@]}; do
    IFS='/' read -r -a route_edit <<< $route
    mask=$(cidr2mask ${route_edit[1]} ${route_edit[0]})
    echo "    - ${route_edit[0]} $mask"
  done
  echo "  vpn_dns_servers:"
  for dns in ${vpn_dns_servers[@]}; do
    echo "    - $dns"
  done
  echo "  vpn_dns_search_domains:"
  for domain in ${vpn_dns_search_domains[@]}; do
    echo "    - $domain"
  done
  echo
fi
) >$GENESIS_ROOT/.$GENESIS_ENVIRONMENT.yml


## USERS
prompt_for addusers boolean \
  'Would you like to add users to this jumpbox instance?'

if [[ $addusers == 'true' ]]; then
  echo "  users:" >>$GENESIS_ROOT/.$GENESIS_ENVIRONMENT.yml
fi
while [[ $addusers == 'true' ]]; do
  prompt_for user line \
    'Account login name' \
    --validation '/^[a-z_][a-z0-9_-]{0,30}$/'

  prompt_for shell line \
    "What shell will $user use? (/bin/bash, /bin/zsh, etc.)" \
    --default /bin/bash

  prompt_for pubkey line \
    "What is $user's public SSH key?" \
    --validation '/ssh-/'

  (
  echo "    - name:  $user"
  echo "      shell: $shell"
  echo "      ssh_keys:"
  echo "        # you can add more keys as needed..."
  echo "        - $pubkey"
  echo
  ) >>$GENESIS_ROOT/.$GENESIS_ENVIRONMENT.yml

  prompt_for addusers boolean \
    'Would you like to add another user to this jumpbox instance?'
done

mv $GENESIS_ROOT/.$GENESIS_ENVIRONMENT.yml \
   $GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml

prompt_for edit boolean \
	'Would you like to edit the environment file?'
if [[ $edit = 'true' ]]; then
	exec ${EDITOR:-vim} $GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml
fi
