#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]; then
  declare -a ips
  ips=( $(bosh vms --json | jq -r '.Tables[0].Rows[0].ips') )

      echo; echo;
  describe "#M{$GENESIS_ENVIRONMENT} Jumpbox deployed!"
      echo
      echo "For details about the deployment, run"
      echo
  describe "  #G{$GENESIS_CALL info $GENESIS_ENVIRONMENT}"
      echo
      echo "To access the jumpbox over SSH:"
      echo
  describe "  #G{$GENESIS_CALL do $GENESIS_ENVIRONMENT -- ssh}"
      echo
      echo "or:"
      echo
  describe "  #W{ssh ${ips[0]}}"
      echo
fi
