#!/bin/bash
set -eu
exec 2>&1

prefix=secret/$GENESIS_VAULT_PREFIX

case $GENESIS_SECRET_ACTION in
check)
  rc=0
  if want_feature openvpn ; then
    if ! safe --quiet check $prefix/openvpn/certs/ca; then
      echo "[openvpn/certs/ca] is missing"
      rc=1
    fi
    if ! safe --quiet check $prefix/openvpn/certs/server; then
      echo "[openvpn/certs/server] is missing"
      rc=1
    fi

    [[ $rc == 0 ]] && echo "All secrets and certs present!"
    exit $rc
  else
    echo "No secrets needed (openvpn feature not selected)"
  fi
  ;;

add)
  if want_feature openvpn ; then
    if ! safe --quiet check $prefix/openvpn/certs/ca; then
      echo "[openvpn/certs/ca] generating new openvpn ca certificate"
      safe --quiet x509 issue --ca --name ca.openvpn -u crl_sign -u key_cert_sign $prefix/openvpn/certs/ca
    fi
    if ! safe --quiet check $prefix/openvpn/certs/server; then
      echo "[openvpn/certs/server] generating new openvpn server certificate"
      safe --quiet x509 issue --signed-by $prefix/openvpn/certs/ca --name server.openvpn --ttl 180d -u server_auth -u digital_signature -u key_encipherment $prefix/openvpn/certs/server
    fi
  else
    echo "No secrets needed (openvpn feature not selected)"
  fi
  ;;

rotate)
  if want_feature openvpn ; then
    echo "[openvpn/certs/ca] rotating openvpn ca certificate"
    safe --quiet x509 issue --ca --name ca.openvpn -u crl_sign -u key_cert_sign $prefix/openvpn/certs/ca
    echo "[openvpn/certs/server] rotating openvpn server certificate"
    safe --quiet x509 issue --signed-by $prefix/openvpn/certs/ca --name server.openvpn --ttl 180d -u server_auth -u digital_signature -u key_encipherment $prefix/openvpn/certs/server
  else
    echo "No secrets needed (openvpn feature not selected)"
  fi
  ;;

default)
  echo >&2 "unrecognized 'hooks/secret' action: '$GENESIS_SECRET_ACTION'"
  exit 2
esac

exit 0
