#!/bin/bash
set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk $disk"
			$BOSH -n delete-disk "$disk"
		done
	done
}

header "Validating BOSH_* environment variables..."
set | grep BOSH_ || true

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-jumpbox
safe rm -rf secret/genesis-ci/jumpbox
safe ssh secret/genesis-ci/jumpbox/TEMP/test-user-ssh-key
# ci-baseline doesn't rely on external secrets
#safe cp -rf secret/genesis-ci/static/jumpbox secret/genesis-ci/jumpbox/ci/baseline

header "Deploying BASELINE environment to verify functionality..."
genesis secrets --vault da-vault add ci-baseline
genesis deploy -n ci-baseline
$BOSH -d ci-baseline-jumpbox instances --ps

header "Validating BASELINE environment (via acceptance-tests errand)"
$BOSH -d ci-baseline-jumpbox run-errand acceptance-tests

header "Cleaning up BASELINE environment..."
cleanup ci-baseline-jumpbox
